languageCode: "en-us"
baseurl: "http://stevemorin.github.io/"
title: "Steve Morin"
theme: "herring-cove"
newcontentEditor: "vim"

params:
  ProfilePicture: "http://www.dailystormer.com/wp-content/uploads/2015/02/joe-rogan.jpg"
  links:
    Home: "/"
    Blog: "/blog/"
    About: "/about/"

  AuthorName: "Steve Morin"
